---
abstract: 'Compile .scss files using libsass'
author:
  - 'David Caldwell <david@porkrind.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Sass
provides:
  CSS::Sass:
    file: lib/CSS/Sass.pm
    version: v0.2.0
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.0
