---
abstract: 'Compile .scss files using libsass'
author:
  - 'David Caldwell <david@porkrind.org>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-Sass
provides:
  CSS::Sass:
    file: lib/CSS/Sass.pm
    version: v0.8.1
  CSS::Sass::Type:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Boolean:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Color:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Dimension:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Error:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::List:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Number:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::Percentage:
    file: lib/CSS/Sass/Type.pm
  CSS::Sass::Type::String:
    file: lib/CSS/Sass/Type.pm
requires:
  Class::Accessor::Fast: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.8.1
